name: Hello

on: 
  workflow_dispatch:

jobs: 
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print some context
        run: |
          echo: "Repo:   $GITHUB_REPOSITORY"
          echo: "Ref:    $GITHUB_REF"
          echo: "SHA:    $GITHUB_SHA"
          echo: "Actor:  $GITHUB_ACTOR"
          echo: "Event:  $GITHUB_EVENT_NAME"
          echo: "Runner: $RUNNER_OS"

      - name: Look at Machine
        run: |
          uname -a
          echo "---CPU/RAM--"
          nproc && free -h
          echo "---preinstalled---"
          python3 --version && git --version && docker --version